name: Mintlify Preview Deploy

on:
  pull_request:
    paths:
      - '**'       # en, ko, docs.json 전부 트리거됨
    types:
      - opened
      - synchronize
      - reopened

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Mintlify Preview
        uses: frain-dev/mintlify-preview-action@v0.1.3
        with:
          docs_path: "docs.json"   # 루트에 있기 때문에 이렇게 해야 함
          github_token: ${{ secrets.GITHUB_TOKEN }}
